// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cred.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CredReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredReq) Reset()         { *m = CredReq{} }
func (m *CredReq) String() string { return proto.CompactTextString(m) }
func (*CredReq) ProtoMessage()    {}
func (*CredReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19cefea999b106e, []int{0}
}

func (m *CredReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredReq.Unmarshal(m, b)
}
func (m *CredReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredReq.Marshal(b, m, deterministic)
}
func (m *CredReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredReq.Merge(m, src)
}
func (m *CredReq) XXX_Size() int {
	return xxx_messageInfo_CredReq.Size(m)
}
func (m *CredReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CredReq.DiscardUnknown(m)
}

var xxx_messageInfo_CredReq proto.InternalMessageInfo

func (m *CredReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CredReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateCredResp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	File                 []byte    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	ErrorMsg             *ErrorMsg `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCredResp) Reset()         { *m = CreateCredResp{} }
func (m *CreateCredResp) String() string { return proto.CompactTextString(m) }
func (*CreateCredResp) ProtoMessage()    {}
func (*CreateCredResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19cefea999b106e, []int{1}
}

func (m *CreateCredResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredResp.Unmarshal(m, b)
}
func (m *CreateCredResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredResp.Marshal(b, m, deterministic)
}
func (m *CreateCredResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredResp.Merge(m, src)
}
func (m *CreateCredResp) XXX_Size() int {
	return xxx_messageInfo_CreateCredResp.Size(m)
}
func (m *CreateCredResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredResp proto.InternalMessageInfo

func (m *CreateCredResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateCredResp) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *CreateCredResp) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type CheckCredResp struct {
	ResponseCode         int32     `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ErrorMsg             *ErrorMsg `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckCredResp) Reset()         { *m = CheckCredResp{} }
func (m *CheckCredResp) String() string { return proto.CompactTextString(m) }
func (*CheckCredResp) ProtoMessage()    {}
func (*CheckCredResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19cefea999b106e, []int{2}
}

func (m *CheckCredResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckCredResp.Unmarshal(m, b)
}
func (m *CheckCredResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckCredResp.Marshal(b, m, deterministic)
}
func (m *CheckCredResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckCredResp.Merge(m, src)
}
func (m *CheckCredResp) XXX_Size() int {
	return xxx_messageInfo_CheckCredResp.Size(m)
}
func (m *CheckCredResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckCredResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckCredResp proto.InternalMessageInfo

func (m *CheckCredResp) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *CheckCredResp) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

func init() {
	proto.RegisterType((*CredReq)(nil), "RoomStatus.CredReq")
	proto.RegisterType((*CreateCredResp)(nil), "RoomStatus.CreateCredResp")
	proto.RegisterType((*CheckCredResp)(nil), "RoomStatus.CheckCredResp")
}

func init() { proto.RegisterFile("cred.proto", fileDescriptor_c19cefea999b106e) }

var fileDescriptor_c19cefea999b106e = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xd5, 0xb8, 0x5f, 0xbe, 0x36, 0xd3, 0x26, 0xa0, 0x69, 0x17, 0xa9, 0x41, 0x51, 0x64, 0x36,
	0x28, 0x22, 0x9e, 0x34, 0x5d, 0x20, 0xb2, 0x2b, 0x06, 0x95, 0x2c, 0x2a, 0x05, 0xd3, 0xb2, 0x80,
	0x45, 0x35, 0x71, 0x6e, 0x27, 0x56, 0x6d, 0xcf, 0x30, 0x33, 0x49, 0x95, 0x2d, 0x12, 0x2f, 0x00,
	0x2b, 0x5e, 0x81, 0xa7, 0x60, 0xd9, 0x25, 0x12, 0x2f, 0x80, 0x52, 0x1e, 0x04, 0x79, 0x92, 0x26,
	0x2e, 0x02, 0x04, 0x2b, 0xdf, 0xf3, 0xe3, 0x73, 0x46, 0x57, 0x17, 0xe3, 0x48, 0xc1, 0xd0, 0x97,
	0x4a, 0x18, 0x41, 0x70, 0x28, 0x44, 0xfa, 0xc2, 0x30, 0x33, 0xd6, 0xee, 0x1d, 0x2e, 0x04, 0x4f,
	0x80, 0x5a, 0x65, 0x30, 0x3e, 0xa3, 0x90, 0x4a, 0x33, 0x9d, 0x1b, 0xdd, 0xbb, 0x0b, 0x91, 0xc9,
	0x98, 0xb2, 0x2c, 0x13, 0x86, 0x99, 0x58, 0x64, 0x7a, 0xa1, 0x3e, 0xb0, 0x9f, 0xa8, 0xc5, 0x21,
	0x6b, 0xe9, 0x0b, 0xc6, 0x39, 0x28, 0x2a, 0xa4, 0x75, 0xfc, 0xc2, 0xdd, 0xe2, 0xb1, 0x19, 0x8d,
	0x07, 0x7e, 0x24, 0x52, 0xca, 0x05, 0x17, 0xab, 0xc6, 0x1c, 0x59, 0x60, 0xa7, 0x85, 0xbd, 0x72,
	0xc8, 0x52, 0x08, 0x4c, 0x32, 0x87, 0xde, 0x73, 0xbc, 0x1e, 0x28, 0x18, 0x86, 0xf0, 0x86, 0x54,
	0xb1, 0xd3, 0x93, 0x35, 0xd4, 0x40, 0xf7, 0xcb, 0xa1, 0xd3, 0x93, 0xc4, 0xc5, 0x1b, 0x27, 0x1a,
	0x54, 0xc6, 0x52, 0xa8, 0x39, 0x96, 0x5d, 0xe2, 0x5c, 0xeb, 0x33, 0xad, 0x2f, 0x84, 0x1a, 0xd6,
	0xd6, 0xe6, 0xda, 0x35, 0xf6, 0xce, 0x71, 0x35, 0x50, 0xc0, 0x0c, 0xcc, 0x83, 0xb5, 0x24, 0x04,
	0xff, 0x17, 0x89, 0x21, 0xd8, 0xec, 0x52, 0x68, 0xe7, 0x9c, 0x3b, 0x8b, 0x93, 0x79, 0xf2, 0x56,
	0x68, 0x67, 0xb2, 0x87, 0xcb, 0xa0, 0x94, 0x50, 0xa7, 0xa9, 0xe6, 0x36, 0x76, 0xb3, 0xb3, 0xe3,
	0xaf, 0x76, 0xea, 0x3f, 0xcd, 0xc5, 0x23, 0xcd, 0xc3, 0x0d, 0x58, 0x4c, 0x1e, 0xc7, 0x95, 0x60,
	0x04, 0xd1, 0xf9, 0xb2, 0xeb, 0x1e, 0xae, 0x28, 0xd0, 0x52, 0x64, 0x1a, 0x4e, 0x0b, 0xa5, 0x5b,
	0xd7, 0x64, 0x90, 0x97, 0xdf, 0x28, 0x72, 0xfe, 0xa6, 0xa8, 0xf3, 0xd1, 0xc1, 0x9b, 0x79, 0x49,
	0x6c, 0xf4, 0xc1, 0xd8, 0x8c, 0xc8, 0x4b, 0x5c, 0x5e, 0x16, 0x93, 0xed, 0xe2, 0xcf, 0x8b, 0x7d,
	0xba, 0xbb, 0x37, 0xc8, 0xe2, 0x23, 0xbd, 0xdd, 0xb7, 0x5f, 0xbf, 0x7f, 0x70, 0xb6, 0xbd, 0x2a,
	0x9d, 0xec, 0xd1, 0xfc, 0x80, 0x68, 0x94, 0xeb, 0x5d, 0xd4, 0x24, 0x27, 0x78, 0xfd, 0x10, 0xcc,
	0xef, 0x53, 0xdd, 0x9f, 0xc8, 0xc2, 0x9e, 0xff, 0x14, 0xfb, 0x1a, 0xe3, 0x95, 0xf9, 0xdf, 0x93,
	0x5d, 0x9b, 0xbc, 0xe3, 0xdd, 0x5a, 0x25, 0x5b, 0x43, 0x17, 0x35, 0xdb, 0xe8, 0xf1, 0x3b, 0xf4,
	0xfe, 0xe0, 0x98, 0x94, 0x3a, 0x6b, 0x6d, 0xbf, 0xd3, 0x44, 0x8e, 0x7a, 0x86, 0x3d, 0x1e, 0xf6,
	0x83, 0x86, 0x06, 0x35, 0x01, 0xd5, 0xe8, 0xa5, 0x32, 0x01, 0x03, 0x29, 0x64, 0xa6, 0xa1, 0x40,
	0x0a, 0x1d, 0x1b, 0xa1, 0xa6, 0xc4, 0x1b, 0x19, 0x23, 0x75, 0x97, 0xd2, 0xc2, 0x01, 0x6b, 0x33,
	0x89, 0x46, 0xe9, 0xa3, 0x87, 0xed, 0x7d, 0xda, 0x7b, 0x12, 0x1c, 0x5f, 0xce, 0xea, 0xe8, 0xcb,
	0xac, 0x8e, 0xbe, 0xcd, 0xea, 0xe8, 0xf3, 0x55, 0x1d, 0x5d, 0x5e, 0xd5, 0xd1, 0xab, 0x92, 0xbd,
	0xdc, 0x4f, 0xce, 0xed, 0x7e, 0xc2, 0xa6, 0x41, 0x12, 0xfb, 0xfd, 0x1c, 0x1f, 0x89, 0xe1, 0xe0,
	0x7f, 0xab, 0xec, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x32, 0x77, 0xb5, 0x00, 0x94, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CreditsAuthClient is the client API for CreditsAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreditsAuthClient interface {
	CheckCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (*CheckCredResp, error)
	GetCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (*CreateCredResp, error)
	CreateCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (CreditsAuth_CreateCredClient, error)
}

type creditsAuthClient struct {
	cc *grpc.ClientConn
}

func NewCreditsAuthClient(cc *grpc.ClientConn) CreditsAuthClient {
	return &creditsAuthClient{cc}
}

func (c *creditsAuthClient) CheckCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (*CheckCredResp, error) {
	out := new(CheckCredResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.CreditsAuth/CheckCred", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditsAuthClient) GetCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (*CreateCredResp, error) {
	out := new(CreateCredResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.CreditsAuth/GetCred", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *creditsAuthClient) CreateCred(ctx context.Context, in *CredReq, opts ...grpc.CallOption) (CreditsAuth_CreateCredClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CreditsAuth_serviceDesc.Streams[0], "/RoomStatus.CreditsAuth/CreateCred", opts...)
	if err != nil {
		return nil, err
	}
	x := &creditsAuthCreateCredClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CreditsAuth_CreateCredClient interface {
	Recv() (*CreateCredResp, error)
	grpc.ClientStream
}

type creditsAuthCreateCredClient struct {
	grpc.ClientStream
}

func (x *creditsAuthCreateCredClient) Recv() (*CreateCredResp, error) {
	m := new(CreateCredResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CreditsAuthServer is the server API for CreditsAuth service.
type CreditsAuthServer interface {
	CheckCred(context.Context, *CredReq) (*CheckCredResp, error)
	GetCred(context.Context, *CredReq) (*CreateCredResp, error)
	CreateCred(*CredReq, CreditsAuth_CreateCredServer) error
}

// UnimplementedCreditsAuthServer can be embedded to have forward compatible implementations.
type UnimplementedCreditsAuthServer struct {
}

func (*UnimplementedCreditsAuthServer) CheckCred(ctx context.Context, req *CredReq) (*CheckCredResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCred not implemented")
}
func (*UnimplementedCreditsAuthServer) GetCred(ctx context.Context, req *CredReq) (*CreateCredResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCred not implemented")
}
func (*UnimplementedCreditsAuthServer) CreateCred(req *CredReq, srv CreditsAuth_CreateCredServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateCred not implemented")
}

func RegisterCreditsAuthServer(s *grpc.Server, srv CreditsAuthServer) {
	s.RegisterService(&_CreditsAuth_serviceDesc, srv)
}

func _CreditsAuth_CheckCred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditsAuthServer).CheckCred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.CreditsAuth/CheckCred",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditsAuthServer).CheckCred(ctx, req.(*CredReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditsAuth_GetCred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreditsAuthServer).GetCred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.CreditsAuth/GetCred",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreditsAuthServer).GetCred(ctx, req.(*CredReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CreditsAuth_CreateCred_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CredReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CreditsAuthServer).CreateCred(m, &creditsAuthCreateCredServer{stream})
}

type CreditsAuth_CreateCredServer interface {
	Send(*CreateCredResp) error
	grpc.ServerStream
}

type creditsAuthCreateCredServer struct {
	grpc.ServerStream
}

func (x *creditsAuthCreateCredServer) Send(m *CreateCredResp) error {
	return x.ServerStream.SendMsg(m)
}

var _CreditsAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoomStatus.CreditsAuth",
	HandlerType: (*CreditsAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCred",
			Handler:    _CreditsAuth_CheckCred_Handler,
		},
		{
			MethodName: "GetCred",
			Handler:    _CreditsAuth_GetCred_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateCred",
			Handler:       _CreditsAuth_CreateCred_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cred.proto",
}
