// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: GameCtl.proto

package proto

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_ON_START     Status = 0
	Status_ON_WAIT      Status = 1
	Status_ON_HOST_TURN Status = 2
	Status_ON_DUEL_TURN Status = 3
	Status_ON_END       Status = 4
)

var Status_name = map[int32]string{
	0: "ON_START",
	1: "ON_WAIT",
	2: "ON_HOST_TURN",
	3: "ON_DUEL_TURN",
	4: "ON_END",
}

var Status_value = map[string]int32{
	"ON_START":     0,
	"ON_WAIT":      1,
	"ON_HOST_TURN": 2,
	"ON_DUEL_TURN": 3,
	"ON_END":       4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{0}
}

type RoomListRequest struct {
	Requirement          string   `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomListRequest) Reset()         { *m = RoomListRequest{} }
func (m *RoomListRequest) String() string { return proto.CompactTextString(m) }
func (*RoomListRequest) ProtoMessage()    {}
func (*RoomListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{0}
}
func (m *RoomListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListRequest.Unmarshal(m, b)
}
func (m *RoomListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListRequest.Marshal(b, m, deterministic)
}
func (m *RoomListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListRequest.Merge(m, src)
}
func (m *RoomListRequest) XXX_Size() int {
	return xxx_messageInfo_RoomListRequest.Size(m)
}
func (m *RoomListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListRequest proto.InternalMessageInfo

func (m *RoomListRequest) GetRequirement() string {
	if m != nil {
		return m.Requirement
	}
	return ""
}

type RoomListResponse struct {
	Result               []*Room  `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomListResponse) Reset()         { *m = RoomListResponse{} }
func (m *RoomListResponse) String() string { return proto.CompactTextString(m) }
func (*RoomListResponse) ProtoMessage()    {}
func (*RoomListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{1}
}
func (m *RoomListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListResponse.Unmarshal(m, b)
}
func (m *RoomListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListResponse.Marshal(b, m, deterministic)
}
func (m *RoomListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListResponse.Merge(m, src)
}
func (m *RoomListResponse) XXX_Size() int {
	return xxx_messageInfo_RoomListResponse.Size(m)
}
func (m *RoomListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListResponse proto.InternalMessageInfo

func (m *RoomListResponse) GetResult() []*Room {
	if m != nil {
		return m.Result
	}
	return nil
}

type RoomRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{2}
}
func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

func (m *RoomRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Room struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HostId               string        `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Status               Status        `protobuf:"varint,3,opt,name=status,proto3,enum=RoomStatus.Status" json:"status,omitempty"`
	Round                int32         `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Cell                 int32         `protobuf:"varint,5,opt,name=cell,proto3" json:"cell,omitempty"`
	CellStatus           []*CellStatus `protobuf:"bytes,6,rep,name=cell_status,json=cellStatus,proto3" json:"cell_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{3}
}
func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Room) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Room) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ON_START
}

func (m *Room) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Room) GetCell() int32 {
	if m != nil {
		return m.Cell
	}
	return 0
}

func (m *Room) GetCellStatus() []*CellStatus {
	if m != nil {
		return m.CellStatus
	}
	return nil
}

type CellStatus struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Turn                 int32    `protobuf:"varint,2,opt,name=turn,proto3" json:"turn,omitempty"`
	CellNum              int32    `protobuf:"varint,3,opt,name=cell_num,json=cellNum,proto3" json:"cell_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellStatus) Reset()         { *m = CellStatus{} }
func (m *CellStatus) String() string { return proto.CompactTextString(m) }
func (*CellStatus) ProtoMessage()    {}
func (*CellStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_844dd485888a1988, []int{4}
}
func (m *CellStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellStatus.Unmarshal(m, b)
}
func (m *CellStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellStatus.Marshal(b, m, deterministic)
}
func (m *CellStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellStatus.Merge(m, src)
}
func (m *CellStatus) XXX_Size() int {
	return xxx_messageInfo_CellStatus.Size(m)
}
func (m *CellStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CellStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CellStatus proto.InternalMessageInfo

func (m *CellStatus) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CellStatus) GetTurn() int32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *CellStatus) GetCellNum() int32 {
	if m != nil {
		return m.CellNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("RoomStatus.Status", Status_name, Status_value)
	proto.RegisterType((*RoomListRequest)(nil), "RoomStatus.RoomListRequest")
	proto.RegisterType((*RoomListResponse)(nil), "RoomStatus.RoomListResponse")
	proto.RegisterType((*RoomRequest)(nil), "RoomStatus.RoomRequest")
	proto.RegisterType((*Room)(nil), "RoomStatus.Room")
	proto.RegisterType((*CellStatus)(nil), "RoomStatus.CellStatus")
}

func init() { proto.RegisterFile("GameCtl.proto", fileDescriptor_844dd485888a1988) }

var fileDescriptor_844dd485888a1988 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6e, 0xd3, 0x50,
	0x10, 0xc5, 0x89, 0xed, 0x96, 0x71, 0x4b, 0xad, 0x51, 0xd5, 0x1a, 0xb7, 0x12, 0x91, 0x57, 0x51,
	0x16, 0x36, 0xb4, 0x0b, 0xa4, 0x88, 0x4d, 0x49, 0xa2, 0x12, 0xa9, 0x75, 0x2a, 0x27, 0x11, 0x82,
	0x45, 0x2d, 0x27, 0xfe, 0x29, 0x16, 0xb6, 0x7f, 0x6a, 0x7f, 0x23, 0x65, 0xcb, 0x15, 0xb8, 0x05,
	0x47, 0x60, 0xc5, 0x1d, 0xb8, 0x02, 0x07, 0x41, 0xfe, 0xfe, 0x6d, 0x22, 0x92, 0x20, 0x56, 0x9e,
	0x99, 0x37, 0xff, 0x3d, 0xcf, 0xcc, 0x83, 0xfd, 0xcb, 0x20, 0x21, 0x1d, 0x16, 0xdb, 0xf3, 0x8c,
	0x32, 0x8a, 0xe0, 0x51, 0x9a, 0x0c, 0x59, 0xc0, 0x8a, 0xdc, 0x3c, 0xb9, 0xa3, 0xf4, 0x2e, 0x26,
	0x0e, 0x47, 0x26, 0xc5, 0xcc, 0x21, 0xc9, 0x9c, 0x2d, 0xaa, 0x46, 0xf3, 0x54, 0x80, 0xc1, 0x3c,
	0x72, 0x82, 0x34, 0xa5, 0x2c, 0x60, 0x11, 0x4d, 0xf3, 0x0a, 0xb5, 0xce, 0xe1, 0xa0, 0x24, 0xba,
	0x8a, 0x72, 0xe6, 0x91, 0xfb, 0x82, 0xe4, 0x0c, 0x1b, 0xa0, 0x65, 0xe4, 0xbe, 0x88, 0x32, 0x92,
	0x90, 0x94, 0x19, 0x52, 0x43, 0x6a, 0x3e, 0xf5, 0x56, 0x4b, 0xd6, 0x1b, 0xd0, 0x97, 0x8f, 0xf2,
	0x39, 0x4d, 0x73, 0x82, 0x4d, 0x50, 0x33, 0x92, 0x17, 0x71, 0xf9, 0xa0, 0xde, 0xd4, 0xce, 0x74,
	0x7b, 0xf9, 0x83, 0x3c, 0xf4, 0x04, 0x6e, 0xbd, 0x00, 0x8d, 0xe7, 0x42, 0x4e, 0x87, 0xfa, 0x67,
	0xb2, 0x10, 0x32, 0x65, 0x68, 0xfd, 0x94, 0x40, 0x2e, 0x3b, 0xd6, 0x21, 0x3c, 0x86, 0x9d, 0x4f,
	0x34, 0x67, 0x7e, 0x14, 0x1a, 0x35, 0x5e, 0x55, 0xcb, 0xb4, 0x1f, 0x62, 0x0b, 0xd4, 0x9c, 0x6b,
	0x19, 0xf5, 0x86, 0xd4, 0x7c, 0x76, 0x86, 0xab, 0xf2, 0xd5, 0xc7, 0x13, 0x1d, 0x78, 0x08, 0x4a,
	0x46, 0x8b, 0x34, 0x34, 0xe4, 0x86, 0xd4, 0x54, 0xbc, 0x2a, 0x41, 0x04, 0x79, 0x4a, 0xe2, 0xd8,
	0x50, 0x78, 0x91, 0xc7, 0xf8, 0x1a, 0xb4, 0xf2, 0xeb, 0x0b, 0x6a, 0x95, 0x4f, 0x76, 0xb4, 0x4a,
	0xdd, 0x21, 0x71, 0x2c, 0xe8, 0x61, 0xfa, 0x18, 0x5b, 0xd7, 0x00, 0x4b, 0x64, 0xc3, 0x1c, 0x08,
	0x32, 0x2b, 0xb2, 0x94, 0x0f, 0xa1, 0x78, 0x3c, 0xc6, 0xe7, 0xb0, 0xcb, 0xc5, 0xd2, 0x22, 0xe1,
	0x43, 0x28, 0xde, 0x4e, 0x99, 0xbb, 0x45, 0xd2, 0x1a, 0x82, 0x2a, 0xa8, 0xf6, 0x60, 0x77, 0xe0,
	0xfa, 0xc3, 0xd1, 0x85, 0x37, 0xd2, 0x9f, 0xa0, 0x06, 0x3b, 0x03, 0xd7, 0x7f, 0x7f, 0xd1, 0x1f,
	0xe9, 0x12, 0xea, 0xb0, 0x37, 0x70, 0xfd, 0x77, 0x83, 0xe1, 0xc8, 0x1f, 0x8d, 0x3d, 0x57, 0xaf,
	0x89, 0x4a, 0x77, 0xdc, 0xbb, 0xaa, 0x2a, 0x75, 0x04, 0x50, 0x07, 0xae, 0xdf, 0x73, 0xbb, 0xba,
	0x7c, 0xf6, 0x43, 0x86, 0x15, 0x13, 0xa1, 0x07, 0xd0, 0xc9, 0x48, 0xc0, 0x08, 0x5f, 0xfd, 0x91,
	0x5d, 0xd9, 0xc6, 0x7e, 0xf0, 0x94, 0xdd, 0x2b, 0x3d, 0x65, 0xae, 0x9d, 0xd5, 0x32, 0xbf, 0xfe,
	0xfa, 0xfd, 0xad, 0x76, 0x68, 0x1d, 0x38, 0x5f, 0x5e, 0x39, 0x19, 0xa5, 0x89, 0x33, 0xe5, 0x34,
	0x6d, 0xa9, 0x85, 0x13, 0xd0, 0x2e, 0x09, 0x7b, 0xf0, 0x0a, 0x9e, 0xfc, 0xfd, 0x78, 0xc5, 0x76,
	0xe6, 0xe9, 0x66, 0xb0, 0xb2, 0x97, 0x65, 0x70, 0x15, 0xb4, 0xf6, 0x1f, 0x55, 0xe2, 0x28, 0x67,
	0xa5, 0xc6, 0x07, 0x40, 0xa1, 0xd1, 0x29, 0xb2, 0x8c, 0xa4, 0xac, 0x9f, 0xce, 0x28, 0x1e, 0xaf,
	0xd9, 0x4f, 0xc8, 0xac, 0x0f, 0xb0, 0x4e, 0x1d, 0xa5, 0x33, 0x5a, 0x52, 0xdf, 0xc2, 0xbe, 0xa0,
	0x1e, 0xb2, 0x8c, 0x04, 0xc9, 0x76, 0xd6, 0x2d, 0x9e, 0xd8, 0xb0, 0x9c, 0x9c, 0x33, 0xb5, 0xa5,
	0xd6, 0x4b, 0x09, 0x6f, 0x41, 0x1f, 0xcf, 0x43, 0xb1, 0x72, 0x71, 0x86, 0x2d, 0x4c, 0xe6, 0x96,
	0x83, 0x6c, 0x50, 0x28, 0x38, 0x65, 0xb5, 0x1a, 0xe8, 0x92, 0x98, 0x88, 0x93, 0xfe, 0xe3, 0xe7,
	0xff, 0x97, 0x3a, 0xe4, 0x6c, 0x6d, 0xa9, 0xf5, 0xd6, 0xfc, 0xa8, 0xf0, 0xee, 0xef, 0x35, 0xfd,
	0x26, 0x0e, 0x16, 0x9d, 0x38, 0xb2, 0x6f, 0xca, 0xfc, 0x9a, 0x86, 0x13, 0x95, 0x23, 0xe7, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x3d, 0xed, 0x01, 0xb2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomStatusClient is the client API for RoomStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomStatusClient interface {
	CreateRoom(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*Room, error)
	GetRoomList(ctx context.Context, in *RoomListRequest, opts ...grpc.CallOption) (*RoomListResponse, error)
	GetRoomCurrentInfo(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*Room, error)
	GetRoomStream(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (RoomStatus_GetRoomStreamClient, error)
	UpdateRoomStatus(ctx context.Context, in *CellStatus, opts ...grpc.CallOption) (*types.Empty, error)
	DeleteRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type roomStatusClient struct {
	cc *grpc.ClientConn
}

func NewRoomStatusClient(cc *grpc.ClientConn) RoomStatusClient {
	return &roomStatusClient{cc}
}

func (c *roomStatusClient) CreateRoom(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) GetRoomList(ctx context.Context, in *RoomListRequest, opts ...grpc.CallOption) (*RoomListResponse, error) {
	out := new(RoomListResponse)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/GetRoomList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) GetRoomCurrentInfo(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/GetRoomCurrentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) GetRoomStream(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (RoomStatus_GetRoomStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomStatus_serviceDesc.Streams[0], "/RoomStatus.RoomStatus/GetRoomStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomStatusGetRoomStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoomStatus_GetRoomStreamClient interface {
	Recv() (*CellStatus, error)
	grpc.ClientStream
}

type roomStatusGetRoomStreamClient struct {
	grpc.ClientStream
}

func (x *roomStatusGetRoomStreamClient) Recv() (*CellStatus, error) {
	m := new(CellStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roomStatusClient) UpdateRoomStatus(ctx context.Context, in *CellStatus, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/UpdateRoomStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) DeleteRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/DeleteRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomStatusServer is the server API for RoomStatus service.
type RoomStatusServer interface {
	CreateRoom(context.Context, *types.Empty) (*Room, error)
	GetRoomList(context.Context, *RoomListRequest) (*RoomListResponse, error)
	GetRoomCurrentInfo(context.Context, *RoomRequest) (*Room, error)
	GetRoomStream(*RoomRequest, RoomStatus_GetRoomStreamServer) error
	UpdateRoomStatus(context.Context, *CellStatus) (*types.Empty, error)
	DeleteRoom(context.Context, *RoomRequest) (*types.Empty, error)
}

// UnimplementedRoomStatusServer can be embedded to have forward compatible implementations.
type UnimplementedRoomStatusServer struct {
}

func (*UnimplementedRoomStatusServer) CreateRoom(ctx context.Context, req *types.Empty) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomList(ctx context.Context, req *RoomListRequest) (*RoomListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomList not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomCurrentInfo(ctx context.Context, req *RoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomCurrentInfo not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomStream(req *RoomRequest, srv RoomStatus_GetRoomStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRoomStream not implemented")
}
func (*UnimplementedRoomStatusServer) UpdateRoomStatus(ctx context.Context, req *CellStatus) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoomStatus not implemented")
}
func (*UnimplementedRoomStatusServer) DeleteRoom(ctx context.Context, req *RoomRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}

func RegisterRoomStatusServer(s *grpc.Server, srv RoomStatusServer) {
	s.RegisterService(&_RoomStatus_serviceDesc, srv)
}

func _RoomStatus_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).CreateRoom(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_GetRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).GetRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/GetRoomList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).GetRoomList(ctx, req.(*RoomListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_GetRoomCurrentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).GetRoomCurrentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/GetRoomCurrentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).GetRoomCurrentInfo(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_GetRoomStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RoomRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomStatusServer).GetRoomStream(m, &roomStatusGetRoomStreamServer{stream})
}

type RoomStatus_GetRoomStreamServer interface {
	Send(*CellStatus) error
	grpc.ServerStream
}

type roomStatusGetRoomStreamServer struct {
	grpc.ServerStream
}

func (x *roomStatusGetRoomStreamServer) Send(m *CellStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _RoomStatus_UpdateRoomStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).UpdateRoomStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/UpdateRoomStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).UpdateRoomStatus(ctx, req.(*CellStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).DeleteRoom(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoomStatus.RoomStatus",
	HandlerType: (*RoomStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomStatus_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoomList",
			Handler:    _RoomStatus_GetRoomList_Handler,
		},
		{
			MethodName: "GetRoomCurrentInfo",
			Handler:    _RoomStatus_GetRoomCurrentInfo_Handler,
		},
		{
			MethodName: "UpdateRoomStatus",
			Handler:    _RoomStatus_UpdateRoomStatus_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _RoomStatus_DeleteRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRoomStream",
			Handler:       _RoomStatus_GetRoomStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "GameCtl.proto",
}
