// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v2/GameCtl2.proto

package v2

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Room_Status int32

const (
	Room_ON_START     Room_Status = 0
	Room_ON_WAIT      Room_Status = 1
	Room_ON_HOST_TURN Room_Status = 2
	Room_ON_DUEL_TURN Room_Status = 3
	Room_ON_END       Room_Status = 4
)

var Room_Status_name = map[int32]string{
	0: "ON_START",
	1: "ON_WAIT",
	2: "ON_HOST_TURN",
	3: "ON_DUEL_TURN",
	4: "ON_END",
}

var Room_Status_value = map[string]int32{
	"ON_START":     0,
	"ON_WAIT":      1,
	"ON_HOST_TURN": 2,
	"ON_DUEL_TURN": 3,
	"ON_END":       4,
}

func (x Room_Status) String() string {
	return proto.EnumName(Room_Status_name, int32(x))
}

func (Room_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{7, 0}
}

type ErrorMsg struct {
	MsgInfo              string   `protobuf:"bytes,1,opt,name=msg_info,json=msgInfo,proto3" json:"msg_info,omitempty"`
	MsgDesp              string   `protobuf:"bytes,2,opt,name=msg_desp,json=msgDesp,proto3" json:"msg_desp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMsg) Reset()         { *m = ErrorMsg{} }
func (m *ErrorMsg) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg) ProtoMessage()    {}
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{0}
}

func (m *ErrorMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMsg.Unmarshal(m, b)
}
func (m *ErrorMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMsg.Marshal(b, m, deterministic)
}
func (m *ErrorMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMsg.Merge(m, src)
}
func (m *ErrorMsg) XXX_Size() int {
	return xxx_messageInfo_ErrorMsg.Size(m)
}
func (m *ErrorMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMsg proto.InternalMessageInfo

func (m *ErrorMsg) GetMsgInfo() string {
	if m != nil {
		return m.MsgInfo
	}
	return ""
}

func (m *ErrorMsg) GetMsgDesp() string {
	if m != nil {
		return m.MsgDesp
	}
	return ""
}

type RoomListReq struct {
	Requirement          string   `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomListReq) Reset()         { *m = RoomListReq{} }
func (m *RoomListReq) String() string { return proto.CompactTextString(m) }
func (*RoomListReq) ProtoMessage()    {}
func (*RoomListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{1}
}

func (m *RoomListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListReq.Unmarshal(m, b)
}
func (m *RoomListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListReq.Marshal(b, m, deterministic)
}
func (m *RoomListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListReq.Merge(m, src)
}
func (m *RoomListReq) XXX_Size() int {
	return xxx_messageInfo_RoomListReq.Size(m)
}
func (m *RoomListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListReq proto.InternalMessageInfo

func (m *RoomListReq) GetRequirement() string {
	if m != nil {
		return m.Requirement
	}
	return ""
}

type RoomListResp struct {
	Timestamp            string    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Result               []*Room   `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
	ErrorMsg             *ErrorMsg `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomListResp) Reset()         { *m = RoomListResp{} }
func (m *RoomListResp) String() string { return proto.CompactTextString(m) }
func (*RoomListResp) ProtoMessage()    {}
func (*RoomListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{2}
}

func (m *RoomListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomListResp.Unmarshal(m, b)
}
func (m *RoomListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomListResp.Marshal(b, m, deterministic)
}
func (m *RoomListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomListResp.Merge(m, src)
}
func (m *RoomListResp) XXX_Size() int {
	return xxx_messageInfo_RoomListResp.Size(m)
}
func (m *RoomListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomListResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomListResp proto.InternalMessageInfo

func (m *RoomListResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *RoomListResp) GetResult() []*Room {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *RoomListResp) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type RoomCreateReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreateReq) Reset()         { *m = RoomCreateReq{} }
func (m *RoomCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoomCreateReq) ProtoMessage()    {}
func (*RoomCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{3}
}

func (m *RoomCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateReq.Unmarshal(m, b)
}
func (m *RoomCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateReq.Marshal(b, m, deterministic)
}
func (m *RoomCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateReq.Merge(m, src)
}
func (m *RoomCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoomCreateReq.Size(m)
}
func (m *RoomCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateReq proto.InternalMessageInfo

func (m *RoomCreateReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RoomCreateResp struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to ResponseMsg:
	//	*RoomCreateResp_CellStatus
	//	*RoomCreateResp_ErrorMsg
	ResponseMsg          isRoomCreateResp_ResponseMsg `protobuf_oneof:"response_msg"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RoomCreateResp) Reset()         { *m = RoomCreateResp{} }
func (m *RoomCreateResp) String() string { return proto.CompactTextString(m) }
func (*RoomCreateResp) ProtoMessage()    {}
func (*RoomCreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{4}
}

func (m *RoomCreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateResp.Unmarshal(m, b)
}
func (m *RoomCreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateResp.Marshal(b, m, deterministic)
}
func (m *RoomCreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateResp.Merge(m, src)
}
func (m *RoomCreateResp) XXX_Size() int {
	return xxx_messageInfo_RoomCreateResp.Size(m)
}
func (m *RoomCreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateResp proto.InternalMessageInfo

func (m *RoomCreateResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RoomCreateResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *RoomCreateResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type isRoomCreateResp_ResponseMsg interface {
	isRoomCreateResp_ResponseMsg()
}

type RoomCreateResp_CellStatus struct {
	CellStatus *Room `protobuf:"bytes,4,opt,name=cell_status,json=cellStatus,proto3,oneof"`
}

type RoomCreateResp_ErrorMsg struct {
	ErrorMsg *ErrorMsg `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3,oneof"`
}

func (*RoomCreateResp_CellStatus) isRoomCreateResp_ResponseMsg() {}

func (*RoomCreateResp_ErrorMsg) isRoomCreateResp_ResponseMsg() {}

func (m *RoomCreateResp) GetResponseMsg() isRoomCreateResp_ResponseMsg {
	if m != nil {
		return m.ResponseMsg
	}
	return nil
}

func (m *RoomCreateResp) GetCellStatus() *Room {
	if x, ok := m.GetResponseMsg().(*RoomCreateResp_CellStatus); ok {
		return x.CellStatus
	}
	return nil
}

func (m *RoomCreateResp) GetErrorMsg() *ErrorMsg {
	if x, ok := m.GetResponseMsg().(*RoomCreateResp_ErrorMsg); ok {
		return x.ErrorMsg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoomCreateResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoomCreateResp_CellStatus)(nil),
		(*RoomCreateResp_ErrorMsg)(nil),
	}
}

type RoomReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReq) Reset()         { *m = RoomReq{} }
func (m *RoomReq) String() string { return proto.CompactTextString(m) }
func (*RoomReq) ProtoMessage()    {}
func (*RoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{5}
}

func (m *RoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReq.Unmarshal(m, b)
}
func (m *RoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReq.Marshal(b, m, deterministic)
}
func (m *RoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReq.Merge(m, src)
}
func (m *RoomReq) XXX_Size() int {
	return xxx_messageInfo_RoomReq.Size(m)
}
func (m *RoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReq proto.InternalMessageInfo

func (m *RoomReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RoomResp struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to ResponseMsg:
	//	*RoomResp_RoomInfo
	//	*RoomResp_Error
	ResponseMsg          isRoomResp_ResponseMsg `protobuf_oneof:"response_msg"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoomResp) Reset()         { *m = RoomResp{} }
func (m *RoomResp) String() string { return proto.CompactTextString(m) }
func (*RoomResp) ProtoMessage()    {}
func (*RoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{6}
}

func (m *RoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResp.Unmarshal(m, b)
}
func (m *RoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResp.Marshal(b, m, deterministic)
}
func (m *RoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResp.Merge(m, src)
}
func (m *RoomResp) XXX_Size() int {
	return xxx_messageInfo_RoomResp.Size(m)
}
func (m *RoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResp proto.InternalMessageInfo

func (m *RoomResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type isRoomResp_ResponseMsg interface {
	isRoomResp_ResponseMsg()
}

type RoomResp_RoomInfo struct {
	RoomInfo *Room `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3,oneof"`
}

type RoomResp_Error struct {
	Error *ErrorMsg `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*RoomResp_RoomInfo) isRoomResp_ResponseMsg() {}

func (*RoomResp_Error) isRoomResp_ResponseMsg() {}

func (m *RoomResp) GetResponseMsg() isRoomResp_ResponseMsg {
	if m != nil {
		return m.ResponseMsg
	}
	return nil
}

func (m *RoomResp) GetRoomInfo() *Room {
	if x, ok := m.GetResponseMsg().(*RoomResp_RoomInfo); ok {
		return x.RoomInfo
	}
	return nil
}

func (m *RoomResp) GetError() *ErrorMsg {
	if x, ok := m.GetResponseMsg().(*RoomResp_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoomResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoomResp_RoomInfo)(nil),
		(*RoomResp_Error)(nil),
	}
}

type Room struct {
	Key                  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	HostId               string        `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	DuelerId             string        `protobuf:"bytes,3,opt,name=dueler_id,json=duelerId,proto3" json:"dueler_id,omitempty"`
	Status               Room_Status   `protobuf:"varint,4,opt,name=status,proto3,enum=RoomStatus.Room_Status" json:"status,omitempty"`
	Round                int32         `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
	Cell                 int32         `protobuf:"varint,6,opt,name=cell,proto3" json:"cell,omitempty"`
	CellStatus           []*CellStatus `protobuf:"bytes,7,rep,name=cell_status,json=cellStatus,proto3" json:"cell_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{7}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Room) GetHostId() string {
	if m != nil {
		return m.HostId
	}
	return ""
}

func (m *Room) GetDuelerId() string {
	if m != nil {
		return m.DuelerId
	}
	return ""
}

func (m *Room) GetStatus() Room_Status {
	if m != nil {
		return m.Status
	}
	return Room_ON_START
}

func (m *Room) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Room) GetCell() int32 {
	if m != nil {
		return m.Cell
	}
	return 0
}

func (m *Room) GetCellStatus() []*CellStatus {
	if m != nil {
		return m.CellStatus
	}
	return nil
}

type CellStatus struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Turn                 int32    `protobuf:"varint,2,opt,name=turn,proto3" json:"turn,omitempty"`
	CellNum              int32    `protobuf:"varint,3,opt,name=cell_num,json=cellNum,proto3" json:"cell_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CellStatus) Reset()         { *m = CellStatus{} }
func (m *CellStatus) String() string { return proto.CompactTextString(m) }
func (*CellStatus) ProtoMessage()    {}
func (*CellStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{8}
}

func (m *CellStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellStatus.Unmarshal(m, b)
}
func (m *CellStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellStatus.Marshal(b, m, deterministic)
}
func (m *CellStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellStatus.Merge(m, src)
}
func (m *CellStatus) XXX_Size() int {
	return xxx_messageInfo_CellStatus.Size(m)
}
func (m *CellStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CellStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CellStatus proto.InternalMessageInfo

func (m *CellStatus) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CellStatus) GetTurn() int32 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *CellStatus) GetCellNum() int32 {
	if m != nil {
		return m.CellNum
	}
	return 0
}

type CellStatusReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Player:
	//	*CellStatusReq_IsPlayer
	//	*CellStatusReq_CellStatus
	Player               isCellStatusReq_Player `protobuf_oneof:"player"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CellStatusReq) Reset()         { *m = CellStatusReq{} }
func (m *CellStatusReq) String() string { return proto.CompactTextString(m) }
func (*CellStatusReq) ProtoMessage()    {}
func (*CellStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{9}
}

func (m *CellStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellStatusReq.Unmarshal(m, b)
}
func (m *CellStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellStatusReq.Marshal(b, m, deterministic)
}
func (m *CellStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellStatusReq.Merge(m, src)
}
func (m *CellStatusReq) XXX_Size() int {
	return xxx_messageInfo_CellStatusReq.Size(m)
}
func (m *CellStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CellStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_CellStatusReq proto.InternalMessageInfo

func (m *CellStatusReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CellStatusReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isCellStatusReq_Player interface {
	isCellStatusReq_Player()
}

type CellStatusReq_IsPlayer struct {
	IsPlayer bool `protobuf:"varint,3,opt,name=is_player,json=isPlayer,proto3,oneof"`
}

type CellStatusReq_CellStatus struct {
	CellStatus *CellStatus `protobuf:"bytes,4,opt,name=cell_status,json=cellStatus,proto3,oneof"`
}

func (*CellStatusReq_IsPlayer) isCellStatusReq_Player() {}

func (*CellStatusReq_CellStatus) isCellStatusReq_Player() {}

func (m *CellStatusReq) GetPlayer() isCellStatusReq_Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *CellStatusReq) GetIsPlayer() bool {
	if x, ok := m.GetPlayer().(*CellStatusReq_IsPlayer); ok {
		return x.IsPlayer
	}
	return false
}

func (m *CellStatusReq) GetCellStatus() *CellStatus {
	if x, ok := m.GetPlayer().(*CellStatusReq_CellStatus); ok {
		return x.CellStatus
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CellStatusReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CellStatusReq_IsPlayer)(nil),
		(*CellStatusReq_CellStatus)(nil),
	}
}

type CellStatusResp struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status    int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to ResponseMsg:
	//	*CellStatusResp_CellStatus
	//	*CellStatusResp_ErrorMsg
	ResponseMsg          isCellStatusResp_ResponseMsg `protobuf_oneof:"response_msg"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CellStatusResp) Reset()         { *m = CellStatusResp{} }
func (m *CellStatusResp) String() string { return proto.CompactTextString(m) }
func (*CellStatusResp) ProtoMessage()    {}
func (*CellStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{10}
}

func (m *CellStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CellStatusResp.Unmarshal(m, b)
}
func (m *CellStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CellStatusResp.Marshal(b, m, deterministic)
}
func (m *CellStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CellStatusResp.Merge(m, src)
}
func (m *CellStatusResp) XXX_Size() int {
	return xxx_messageInfo_CellStatusResp.Size(m)
}
func (m *CellStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CellStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_CellStatusResp proto.InternalMessageInfo

func (m *CellStatusResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CellStatusResp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CellStatusResp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CellStatusResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type isCellStatusResp_ResponseMsg interface {
	isCellStatusResp_ResponseMsg()
}

type CellStatusResp_CellStatus struct {
	CellStatus *CellStatus `protobuf:"bytes,5,opt,name=cell_status,json=cellStatus,proto3,oneof"`
}

type CellStatusResp_ErrorMsg struct {
	ErrorMsg *ErrorMsg `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3,oneof"`
}

func (*CellStatusResp_CellStatus) isCellStatusResp_ResponseMsg() {}

func (*CellStatusResp_ErrorMsg) isCellStatusResp_ResponseMsg() {}

func (m *CellStatusResp) GetResponseMsg() isCellStatusResp_ResponseMsg {
	if m != nil {
		return m.ResponseMsg
	}
	return nil
}

func (m *CellStatusResp) GetCellStatus() *CellStatus {
	if x, ok := m.GetResponseMsg().(*CellStatusResp_CellStatus); ok {
		return x.CellStatus
	}
	return nil
}

func (m *CellStatusResp) GetErrorMsg() *ErrorMsg {
	if x, ok := m.GetResponseMsg().(*CellStatusResp_ErrorMsg); ok {
		return x.ErrorMsg
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CellStatusResp) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CellStatusResp_CellStatus)(nil),
		(*CellStatusResp_ErrorMsg)(nil),
	}
}

type CreateCredReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCredReq) Reset()         { *m = CreateCredReq{} }
func (m *CreateCredReq) String() string { return proto.CompactTextString(m) }
func (*CreateCredReq) ProtoMessage()    {}
func (*CreateCredReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{11}
}

func (m *CreateCredReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredReq.Unmarshal(m, b)
}
func (m *CreateCredReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredReq.Marshal(b, m, deterministic)
}
func (m *CreateCredReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredReq.Merge(m, src)
}
func (m *CreateCredReq) XXX_Size() int {
	return xxx_messageInfo_CreateCredReq.Size(m)
}
func (m *CreateCredReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredReq proto.InternalMessageInfo

func (m *CreateCredReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateCredReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateCredReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Cred struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cred) Reset()         { *m = Cred{} }
func (m *Cred) String() string { return proto.CompactTextString(m) }
func (*Cred) ProtoMessage()    {}
func (*Cred) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9ca25efbef8335, []int{12}
}

func (m *Cred) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cred.Unmarshal(m, b)
}
func (m *Cred) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cred.Marshal(b, m, deterministic)
}
func (m *Cred) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cred.Merge(m, src)
}
func (m *Cred) XXX_Size() int {
	return xxx_messageInfo_Cred.Size(m)
}
func (m *Cred) XXX_DiscardUnknown() {
	xxx_messageInfo_Cred.DiscardUnknown(m)
}

var xxx_messageInfo_Cred proto.InternalMessageInfo

func (m *Cred) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func init() {
	proto.RegisterEnum("RoomStatus.Room_Status", Room_Status_name, Room_Status_value)
	proto.RegisterType((*ErrorMsg)(nil), "RoomStatus.ErrorMsg")
	proto.RegisterType((*RoomListReq)(nil), "RoomStatus.RoomListReq")
	proto.RegisterType((*RoomListResp)(nil), "RoomStatus.RoomListResp")
	proto.RegisterType((*RoomCreateReq)(nil), "RoomStatus.RoomCreateReq")
	proto.RegisterType((*RoomCreateResp)(nil), "RoomStatus.RoomCreateResp")
	proto.RegisterType((*RoomReq)(nil), "RoomStatus.RoomReq")
	proto.RegisterType((*RoomResp)(nil), "RoomStatus.RoomResp")
	proto.RegisterType((*Room)(nil), "RoomStatus.Room")
	proto.RegisterType((*CellStatus)(nil), "RoomStatus.CellStatus")
	proto.RegisterType((*CellStatusReq)(nil), "RoomStatus.CellStatusReq")
	proto.RegisterType((*CellStatusResp)(nil), "RoomStatus.CellStatusResp")
	proto.RegisterType((*CreateCredReq)(nil), "RoomStatus.CreateCredReq")
	proto.RegisterType((*Cred)(nil), "RoomStatus.Cred")
}

func init() { proto.RegisterFile("v2/GameCtl2.proto", fileDescriptor_cb9ca25efbef8335) }

var fileDescriptor_cb9ca25efbef8335 = []byte{
	// 1124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xf6, 0x52, 0xff, 0x23, 0xdb, 0x55, 0xb7, 0x86, 0xa3, 0xc8, 0xa9, 0x21, 0xf0, 0x24, 0x18,
	0xb1, 0xe8, 0xc8, 0x87, 0x20, 0x3e, 0xd5, 0x96, 0x8d, 0x58, 0x40, 0x2c, 0xbb, 0x94, 0x0c, 0xa3,
	0xb9, 0x08, 0xb4, 0xb8, 0xa6, 0x89, 0x8a, 0x5c, 0x7a, 0x77, 0xe9, 0xc0, 0xd7, 0xdc, 0x7a, 0x6d,
	0x0f, 0xbd, 0xf5, 0x01, 0xfa, 0x02, 0xbd, 0xf6, 0x98, 0x63, 0x81, 0x9e, 0x7a, 0x2b, 0x9c, 0xbe,
	0x40, 0xde, 0xa0, 0xd8, 0x25, 0x25, 0x51, 0x7f, 0x4e, 0x7f, 0x90, 0x13, 0x77, 0x76, 0x66, 0x67,
	0xbf, 0xf9, 0xf9, 0x86, 0x0b, 0x9f, 0xdf, 0x36, 0x8c, 0x97, 0x96, 0x47, 0x9a, 0x62, 0xd0, 0xa8,
	0x07, 0x8c, 0x0a, 0x8a, 0xc1, 0xa4, 0xd4, 0xeb, 0x08, 0x4b, 0x84, 0xbc, 0xb2, 0xe1, 0x50, 0xea,
	0x0c, 0x88, 0xa1, 0x34, 0x97, 0xe1, 0x95, 0x41, 0xbc, 0x40, 0xdc, 0x45, 0x86, 0x95, 0x27, 0xb1,
	0xd2, 0x0a, 0x5c, 0xc3, 0xf2, 0x7d, 0x2a, 0x2c, 0xe1, 0x52, 0x9f, 0xc7, 0xda, 0xa7, 0xea, 0xd3,
	0xdf, 0x76, 0x88, 0xbf, 0xcd, 0xdf, 0x58, 0x8e, 0x43, 0x98, 0x41, 0x03, 0x65, 0x31, 0xc7, 0x7a,
	0xdb, 0x71, 0xc5, 0x75, 0x78, 0x59, 0xef, 0x53, 0xcf, 0x70, 0xa8, 0x43, 0xc7, 0x37, 0x4a, 0x49,
	0x09, 0x6a, 0x15, 0x99, 0xeb, 0x5f, 0x41, 0xfe, 0x88, 0x31, 0xca, 0x4e, 0xb8, 0x83, 0x1f, 0x43,
	0xde, 0xe3, 0x4e, 0xcf, 0xf5, 0xaf, 0x68, 0x19, 0x55, 0x51, 0xad, 0x60, 0xe6, 0x3c, 0xee, 0xb4,
	0xfc, 0x2b, 0x3a, 0x54, 0xd9, 0x84, 0x07, 0x65, 0x6d, 0xa4, 0x3a, 0x24, 0x3c, 0xd0, 0x0d, 0x28,
	0xca, 0x38, 0x5f, 0xb9, 0x5c, 0x98, 0xe4, 0x06, 0x57, 0xa1, 0xc8, 0xc8, 0x4d, 0xe8, 0x32, 0xe2,
	0x11, 0x5f, 0xc4, 0x7e, 0x92, 0x5b, 0xfa, 0x77, 0x08, 0x96, 0xc7, 0x27, 0x78, 0x80, 0x9f, 0x40,
	0x41, 0xb8, 0x1e, 0xe1, 0xc2, 0xf2, 0x82, 0xf8, 0xc0, 0x78, 0x03, 0xd7, 0x20, 0xcb, 0x08, 0x0f,
	0x07, 0xa2, 0xac, 0x55, 0x53, 0xb5, 0x62, 0xa3, 0x54, 0x1f, 0xa7, 0x55, 0x2d, 0xcd, 0x58, 0x8f,
	0x9f, 0x41, 0x81, 0xc8, 0x58, 0x7a, 0x1e, 0x77, 0xca, 0xa9, 0x2a, 0xaa, 0x15, 0x1b, 0x6b, 0x49,
	0xe3, 0x61, 0xa0, 0x66, 0x9e, 0xc4, 0x2b, 0xbd, 0x06, 0x2b, 0xd2, 0xa0, 0xc9, 0x88, 0x25, 0x88,
	0x84, 0xff, 0x08, 0x72, 0x21, 0x27, 0xac, 0xe7, 0xda, 0x31, 0x92, 0xac, 0x14, 0x5b, 0xb6, 0xfe,
	0x07, 0x82, 0xd5, 0xa4, 0x29, 0x0f, 0x16, 0xda, 0x4e, 0x06, 0xa4, 0x4d, 0x07, 0xb4, 0x0e, 0x59,
	0xae, 0x00, 0x29, 0x8c, 0x19, 0x33, 0x96, 0xf0, 0x2e, 0x14, 0xfb, 0x64, 0x30, 0xe8, 0xc5, 0xca,
	0xb4, 0x0a, 0x60, 0x26, 0xda, 0xe3, 0x25, 0x13, 0xa4, 0x59, 0x67, 0x78, 0x28, 0x11, 0x73, 0x66,
	0x71, 0xcc, 0xc7, 0x4b, 0xe3, 0xa8, 0x0f, 0x56, 0x61, 0x99, 0x11, 0x1e, 0x50, 0x9f, 0x13, 0x79,
	0x4e, 0xdf, 0x80, 0x9c, 0x4a, 0x24, 0xb9, 0xc1, 0x25, 0x48, 0x7d, 0x4b, 0xee, 0xe2, 0x78, 0xe4,
	0x52, 0xff, 0x11, 0x41, 0x3e, 0xd2, 0x7e, 0xb4, 0x54, 0x06, 0x14, 0x18, 0xa5, 0x5e, 0xd4, 0x41,
	0xda, 0x42, 0xfc, 0x79, 0x69, 0xa4, 0xda, 0xea, 0x29, 0x64, 0x14, 0xa8, 0x87, 0xaa, 0x75, 0xbc,
	0x64, 0x46, 0x46, 0x33, 0xb0, 0x7f, 0xd1, 0x20, 0x2d, 0x0f, 0xcc, 0x82, 0x96, 0xa5, 0xb9, 0xa6,
	0x5c, 0xc8, 0xd2, 0x44, 0xf9, 0xcf, 0x4a, 0xb1, 0x65, 0xe3, 0x0d, 0x28, 0xd8, 0x21, 0x19, 0x44,
	0x55, 0x4b, 0x29, 0x55, 0x3e, 0xda, 0x68, 0xd9, 0xd8, 0x18, 0x55, 0x46, 0x26, 0x7f, 0xb5, 0xf1,
	0x68, 0x1a, 0x7c, 0x3d, 0x5a, 0x8f, 0x4a, 0xb6, 0x06, 0x19, 0x46, 0x43, 0xdf, 0x56, 0x99, 0xcf,
	0x98, 0x91, 0x80, 0x31, 0xa4, 0x65, 0x85, 0xca, 0x59, 0xb5, 0xa9, 0xd6, 0xf8, 0xf9, 0x64, 0x71,
	0x73, 0xaa, 0x95, 0xd7, 0x93, 0xfe, 0x9b, 0xa3, 0xa2, 0x26, 0x0b, 0xac, 0x77, 0x20, 0x1b, 0x97,
	0x7a, 0x19, 0xf2, 0xa7, 0xed, 0x5e, 0xa7, 0xbb, 0x6f, 0x76, 0x4b, 0x4b, 0xb8, 0x08, 0xb9, 0xd3,
	0x76, 0xef, 0x62, 0xbf, 0xd5, 0x2d, 0x21, 0x5c, 0x82, 0xe5, 0xd3, 0x76, 0xef, 0xf8, 0xb4, 0xd3,
	0xed, 0x75, 0xcf, 0xcd, 0x76, 0x49, 0x8b, 0x77, 0x0e, 0xcf, 0x8f, 0x5e, 0x45, 0x3b, 0x29, 0x0c,
	0x90, 0x3d, 0x6d, 0xf7, 0x8e, 0xda, 0x87, 0xa5, 0xb4, 0x7e, 0x02, 0x30, 0xbe, 0x6e, 0x4e, 0xfa,
	0x30, 0xa4, 0x45, 0xc8, 0x7c, 0x95, 0xbb, 0x8c, 0xa9, 0xd6, 0x72, 0x04, 0xa8, 0x08, 0xfc, 0xd0,
	0x8b, 0x1b, 0x37, 0x27, 0xe5, 0x76, 0xe8, 0xe9, 0x3f, 0x21, 0x58, 0x49, 0xc0, 0x7f, 0x80, 0x46,
	0xc3, 0xbb, 0xb4, 0xf1, 0x5d, 0x5f, 0x42, 0xc1, 0xe5, 0xbd, 0x60, 0x60, 0xdd, 0x91, 0xa8, 0x0f,
	0xf2, 0xb2, 0x45, 0x5c, 0x7e, 0xa6, 0x76, 0xf0, 0x8b, 0x79, 0xac, 0x58, 0x90, 0xb8, 0x49, 0x6e,
	0x1c, 0xe4, 0x21, 0x1b, 0xb9, 0xd5, 0x3f, 0x20, 0x58, 0x4d, 0x02, 0x7c, 0x88, 0xbc, 0xb3, 0x08,
	0x27, 0x9a, 0x3e, 0xb5, 0x98, 0xce, 0xe9, 0x09, 0x3a, 0x4f, 0x01, 0xcf, 0xfc, 0x73, 0xe0, 0x93,
	0xa4, 0xce, 0xfe, 0x47, 0x52, 0x5f, 0xc0, 0x4a, 0x34, 0xab, 0x9a, 0x8c, 0xd8, 0xb2, 0x26, 0xab,
	0xa0, 0xb5, 0x86, 0xa4, 0xd5, 0x5a, 0x01, 0xae, 0x40, 0xfe, 0x9c, 0x13, 0xe6, 0x5b, 0x1e, 0x89,
	0xa3, 0x1d, 0xc9, 0x52, 0x77, 0x66, 0x71, 0xfe, 0x86, 0xb2, 0x11, 0x4b, 0x86, 0xb2, 0x5e, 0x81,
	0xb4, 0x74, 0x29, 0x9b, 0xe4, 0xca, 0x1d, 0x90, 0xd8, 0xa3, 0x5a, 0x37, 0x3e, 0x64, 0x20, 0xf1,
	0xd7, 0xc3, 0xdf, 0x00, 0xc4, 0xf3, 0x52, 0xd2, 0xf4, 0xf1, 0x34, 0x9d, 0x46, 0x63, 0xb7, 0xb2,
	0x36, 0x33, 0xd4, 0xe5, 0xaf, 0xa5, 0xf2, 0xf6, 0xf7, 0xbf, 0x7e, 0xd0, 0xd6, 0xf4, 0xcf, 0x8c,
	0xdb, 0x67, 0x86, 0x1c, 0x1a, 0x46, 0x5f, 0x9d, 0xd8, 0x43, 0x5b, 0xf8, 0x35, 0x14, 0x5f, 0x12,
	0x31, 0xfc, 0x8f, 0xe0, 0x19, 0xaa, 0xc6, 0xff, 0xa3, 0x4a, 0x79, 0xbe, 0x82, 0x07, 0x7a, 0x59,
	0x79, 0xc7, 0xfa, 0xca, 0xc8, 0xfb, 0xc0, 0xe5, 0x42, 0xfa, 0x36, 0x47, 0xbe, 0xd5, 0x94, 0xfa,
	0x62, 0x16, 0xdc, 0x22, 0xc4, 0xb3, 0x3e, 0xe5, 0x2c, 0x94, 0x3e, 0x3b, 0x00, 0x87, 0x64, 0x40,
	0xe2, 0x54, 0xfc, 0x0b, 0x97, 0xb3, 0x49, 0xb0, 0x95, 0x1f, 0xe9, 0xb4, 0x3f, 0xcc, 0x36, 0x23,
	0xd6, 0x54, 0x7e, 0x27, 0xf8, 0x58, 0xa9, 0x2c, 0x52, 0xcd, 0xbd, 0x80, 0x2b, 0x7f, 0x7b, 0x68,
	0xab, 0x86, 0x76, 0x10, 0xb6, 0x61, 0x25, 0xce, 0xc6, 0x27, 0xbb, 0x67, 0x07, 0xe1, 0x1e, 0xc0,
	0x79, 0x60, 0xcf, 0x6d, 0x95, 0xff, 0x73, 0x45, 0xa8, 0x7c, 0xca, 0x5c, 0x5d, 0x40, 0xfe, 0xeb,
	0xd0, 0x15, 0x1f, 0xeb, 0xc4, 0xf5, 0x7a, 0xf4, 0x18, 0xab, 0x0f, 0xdf, 0x4d, 0xf5, 0x23, 0xf9,
	0x52, 0x9b, 0x53, 0xd9, 0x9b, 0xd0, 0x95, 0xdd, 0xd2, 0xb8, 0x82, 0xa2, 0xe4, 0x83, 0x2b, 0xf8,
	0x7e, 0x28, 0xae, 0xf1, 0xc5, 0xb0, 0xe7, 0x15, 0x49, 0x26, 0x03, 0x49, 0xf2, 0xb1, 0x52, 0x9a,
	0x52, 0xd9, 0x93, 0xf0, 0xfb, 0x8c, 0xd8, 0xe3, 0x7e, 0xdf, 0x41, 0x07, 0x6f, 0xd1, 0xf7, 0xfb,
	0x5d, 0x9c, 0x69, 0xa4, 0x76, 0xea, 0x8d, 0x2d, 0xa4, 0xb1, 0x63, 0xd0, 0x1d, 0xf3, 0xac, 0x59,
	0xe5, 0x84, 0xdd, 0x12, 0x56, 0x6d, 0x79, 0x81, 0x6c, 0x0b, 0xf9, 0xc4, 0xaa, 0x32, 0x12, 0x50,
	0xee, 0x0a, 0xca, 0xee, 0xb0, 0x7e, 0x2d, 0x44, 0xc0, 0xf7, 0x0c, 0x23, 0xf1, 0x2e, 0xe4, 0xe2,
	0xb6, 0x7f, 0xed, 0xbd, 0x78, 0xbe, 0xb3, 0x6b, 0xb4, 0x0e, 0x9b, 0xdd, 0x77, 0xf7, 0x9b, 0xe8,
	0xb7, 0xfb, 0x4d, 0xf4, 0xe7, 0xfd, 0x26, 0xfa, 0xf5, 0xfd, 0x26, 0x7a, 0xf7, 0x7e, 0x13, 0xbd,
	0xd6, 0x6e, 0x1b, 0x3f, 0x6b, 0x25, 0x39, 0x84, 0x9b, 0x03, 0xb7, 0x7e, 0x26, 0x93, 0x71, 0x42,
	0xed, 0xcb, 0xac, 0x4a, 0xcb, 0xee, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0xfb, 0x90, 0x25,
	0xef, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomStatusClient is the client API for RoomStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomStatusClient interface {
	CreateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*RoomResp, error)
	GetRoomList(ctx context.Context, in *RoomListReq, opts ...grpc.CallOption) (*RoomListResp, error)
	GetRoomInfo(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomResp, error)
	DeleteRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomResp, error)
	RoomStream(ctx context.Context, opts ...grpc.CallOption) (RoomStatus_RoomStreamClient, error)
	GetRoomStream(ctx context.Context, in *CellStatusReq, opts ...grpc.CallOption) (RoomStatus_GetRoomStreamClient, error)
	UpdateRoom(ctx context.Context, in *CellStatusReq, opts ...grpc.CallOption) (*CellStatusResp, error)
	QuitRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*types.Empty, error)
}

type roomStatusClient struct {
	cc *grpc.ClientConn
}

func NewRoomStatusClient(cc *grpc.ClientConn) RoomStatusClient {
	return &roomStatusClient{cc}
}

func (c *roomStatusClient) CreateRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*RoomResp, error) {
	out := new(RoomResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) GetRoomList(ctx context.Context, in *RoomListReq, opts ...grpc.CallOption) (*RoomListResp, error) {
	out := new(RoomListResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/GetRoomList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) GetRoomInfo(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomResp, error) {
	out := new(RoomResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/GetRoomInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) DeleteRoom(ctx context.Context, in *RoomReq, opts ...grpc.CallOption) (*RoomResp, error) {
	out := new(RoomResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/DeleteRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) RoomStream(ctx context.Context, opts ...grpc.CallOption) (RoomStatus_RoomStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomStatus_serviceDesc.Streams[0], "/RoomStatus.RoomStatus/RoomStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomStatusRoomStreamClient{stream}
	return x, nil
}

type RoomStatus_RoomStreamClient interface {
	Send(*CellStatusReq) error
	Recv() (*CellStatusResp, error)
	grpc.ClientStream
}

type roomStatusRoomStreamClient struct {
	grpc.ClientStream
}

func (x *roomStatusRoomStreamClient) Send(m *CellStatusReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *roomStatusRoomStreamClient) Recv() (*CellStatusResp, error) {
	m := new(CellStatusResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roomStatusClient) GetRoomStream(ctx context.Context, in *CellStatusReq, opts ...grpc.CallOption) (RoomStatus_GetRoomStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoomStatus_serviceDesc.Streams[1], "/RoomStatus.RoomStatus/GetRoomStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &roomStatusGetRoomStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoomStatus_GetRoomStreamClient interface {
	Recv() (*CellStatusResp, error)
	grpc.ClientStream
}

type roomStatusGetRoomStreamClient struct {
	grpc.ClientStream
}

func (x *roomStatusGetRoomStreamClient) Recv() (*CellStatusResp, error) {
	m := new(CellStatusResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *roomStatusClient) UpdateRoom(ctx context.Context, in *CellStatusReq, opts ...grpc.CallOption) (*CellStatusResp, error) {
	out := new(CellStatusResp)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/UpdateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomStatusClient) QuitRoom(ctx context.Context, in *RoomCreateReq, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/RoomStatus.RoomStatus/QuitRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomStatusServer is the server API for RoomStatus service.
type RoomStatusServer interface {
	CreateRoom(context.Context, *RoomCreateReq) (*RoomResp, error)
	GetRoomList(context.Context, *RoomListReq) (*RoomListResp, error)
	GetRoomInfo(context.Context, *RoomReq) (*RoomResp, error)
	DeleteRoom(context.Context, *RoomReq) (*RoomResp, error)
	RoomStream(RoomStatus_RoomStreamServer) error
	GetRoomStream(*CellStatusReq, RoomStatus_GetRoomStreamServer) error
	UpdateRoom(context.Context, *CellStatusReq) (*CellStatusResp, error)
	QuitRoom(context.Context, *RoomCreateReq) (*types.Empty, error)
}

// UnimplementedRoomStatusServer can be embedded to have forward compatible implementations.
type UnimplementedRoomStatusServer struct {
}

func (*UnimplementedRoomStatusServer) CreateRoom(ctx context.Context, req *RoomCreateReq) (*RoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomList(ctx context.Context, req *RoomListReq) (*RoomListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomList not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomInfo(ctx context.Context, req *RoomReq) (*RoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomInfo not implemented")
}
func (*UnimplementedRoomStatusServer) DeleteRoom(ctx context.Context, req *RoomReq) (*RoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}
func (*UnimplementedRoomStatusServer) RoomStream(srv RoomStatus_RoomStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method RoomStream not implemented")
}
func (*UnimplementedRoomStatusServer) GetRoomStream(req *CellStatusReq, srv RoomStatus_GetRoomStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRoomStream not implemented")
}
func (*UnimplementedRoomStatusServer) UpdateRoom(ctx context.Context, req *CellStatusReq) (*CellStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (*UnimplementedRoomStatusServer) QuitRoom(ctx context.Context, req *RoomCreateReq) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitRoom not implemented")
}

func RegisterRoomStatusServer(s *grpc.Server, srv RoomStatusServer) {
	s.RegisterService(&_RoomStatus_serviceDesc, srv)
}

func _RoomStatus_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).CreateRoom(ctx, req.(*RoomCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_GetRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).GetRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/GetRoomList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).GetRoomList(ctx, req.(*RoomListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_GetRoomInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).GetRoomInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/GetRoomInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).GetRoomInfo(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).DeleteRoom(ctx, req.(*RoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_RoomStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoomStatusServer).RoomStream(&roomStatusRoomStreamServer{stream})
}

type RoomStatus_RoomStreamServer interface {
	Send(*CellStatusResp) error
	Recv() (*CellStatusReq, error)
	grpc.ServerStream
}

type roomStatusRoomStreamServer struct {
	grpc.ServerStream
}

func (x *roomStatusRoomStreamServer) Send(m *CellStatusResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *roomStatusRoomStreamServer) Recv() (*CellStatusReq, error) {
	m := new(CellStatusReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RoomStatus_GetRoomStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CellStatusReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoomStatusServer).GetRoomStream(m, &roomStatusGetRoomStreamServer{stream})
}

type RoomStatus_GetRoomStreamServer interface {
	Send(*CellStatusResp) error
	grpc.ServerStream
}

type roomStatusGetRoomStreamServer struct {
	grpc.ServerStream
}

func (x *roomStatusGetRoomStreamServer) Send(m *CellStatusResp) error {
	return x.ServerStream.SendMsg(m)
}

func _RoomStatus_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).UpdateRoom(ctx, req.(*CellStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomStatus_QuitRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomStatusServer).QuitRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RoomStatus.RoomStatus/QuitRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomStatusServer).QuitRoom(ctx, req.(*RoomCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoomStatus.RoomStatus",
	HandlerType: (*RoomStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomStatus_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoomList",
			Handler:    _RoomStatus_GetRoomList_Handler,
		},
		{
			MethodName: "GetRoomInfo",
			Handler:    _RoomStatus_GetRoomInfo_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _RoomStatus_DeleteRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _RoomStatus_UpdateRoom_Handler,
		},
		{
			MethodName: "QuitRoom",
			Handler:    _RoomStatus_QuitRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RoomStream",
			Handler:       _RoomStatus_RoomStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetRoomStream",
			Handler:       _RoomStatus_GetRoomStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v2/GameCtl2.proto",
}

// CreditsAuthClient is the client API for CreditsAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CreditsAuthClient interface {
	CreateCred(ctx context.Context, in *CreateCredReq, opts ...grpc.CallOption) (CreditsAuth_CreateCredClient, error)
}

type creditsAuthClient struct {
	cc *grpc.ClientConn
}

func NewCreditsAuthClient(cc *grpc.ClientConn) CreditsAuthClient {
	return &creditsAuthClient{cc}
}

func (c *creditsAuthClient) CreateCred(ctx context.Context, in *CreateCredReq, opts ...grpc.CallOption) (CreditsAuth_CreateCredClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CreditsAuth_serviceDesc.Streams[0], "/RoomStatus.CreditsAuth/CreateCred", opts...)
	if err != nil {
		return nil, err
	}
	x := &creditsAuthCreateCredClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CreditsAuth_CreateCredClient interface {
	Recv() (*Cred, error)
	grpc.ClientStream
}

type creditsAuthCreateCredClient struct {
	grpc.ClientStream
}

func (x *creditsAuthCreateCredClient) Recv() (*Cred, error) {
	m := new(Cred)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CreditsAuthServer is the server API for CreditsAuth service.
type CreditsAuthServer interface {
	CreateCred(*CreateCredReq, CreditsAuth_CreateCredServer) error
}

// UnimplementedCreditsAuthServer can be embedded to have forward compatible implementations.
type UnimplementedCreditsAuthServer struct {
}

func (*UnimplementedCreditsAuthServer) CreateCred(req *CreateCredReq, srv CreditsAuth_CreateCredServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateCred not implemented")
}

func RegisterCreditsAuthServer(s *grpc.Server, srv CreditsAuthServer) {
	s.RegisterService(&_CreditsAuth_serviceDesc, srv)
}

func _CreditsAuth_CreateCred_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateCredReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CreditsAuthServer).CreateCred(m, &creditsAuthCreateCredServer{stream})
}

type CreditsAuth_CreateCredServer interface {
	Send(*Cred) error
	grpc.ServerStream
}

type creditsAuthCreateCredServer struct {
	grpc.ServerStream
}

func (x *creditsAuthCreateCredServer) Send(m *Cred) error {
	return x.ServerStream.SendMsg(m)
}

var _CreditsAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoomStatus.CreditsAuth",
	HandlerType: (*CreditsAuthServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateCred",
			Handler:       _CreditsAuth_CreateCred_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v2/GameCtl2.proto",
}
